/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpecialtiesRouteImport } from './routes/specialties'
import { Route as ResultatsRouteImport } from './routes/resultats'
import { Route as DebouchesRouteImport } from './routes/debouches'
import { Route as ComparerRouteImport } from './routes/comparer'
import { Route as AiRouteImport } from './routes/ai'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SpecialiteIdRouteImport } from './routes/specialite.$id'

const SpecialtiesRoute = SpecialtiesRouteImport.update({
  id: '/specialties',
  path: '/specialties',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultatsRoute = ResultatsRouteImport.update({
  id: '/resultats',
  path: '/resultats',
  getParentRoute: () => rootRouteImport,
} as any)
const DebouchesRoute = DebouchesRouteImport.update({
  id: '/debouches',
  path: '/debouches',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparerRoute = ComparerRouteImport.update({
  id: '/comparer',
  path: '/comparer',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecialiteIdRoute = SpecialiteIdRouteImport.update({
  id: '/specialite/$id',
  path: '/specialite/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/ai': typeof AiRoute
  '/comparer': typeof ComparerRoute
  '/debouches': typeof DebouchesRoute
  '/resultats': typeof ResultatsRoute
  '/specialties': typeof SpecialtiesRoute
  '/specialite/$id': typeof SpecialiteIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/ai': typeof AiRoute
  '/comparer': typeof ComparerRoute
  '/debouches': typeof DebouchesRoute
  '/resultats': typeof ResultatsRoute
  '/specialties': typeof SpecialtiesRoute
  '/specialite/$id': typeof SpecialiteIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/ai': typeof AiRoute
  '/comparer': typeof ComparerRoute
  '/debouches': typeof DebouchesRoute
  '/resultats': typeof ResultatsRoute
  '/specialties': typeof SpecialtiesRoute
  '/specialite/$id': typeof SpecialiteIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/ai'
    | '/comparer'
    | '/debouches'
    | '/resultats'
    | '/specialties'
    | '/specialite/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/ai'
    | '/comparer'
    | '/debouches'
    | '/resultats'
    | '/specialties'
    | '/specialite/$id'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/ai'
    | '/comparer'
    | '/debouches'
    | '/resultats'
    | '/specialties'
    | '/specialite/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  AiRoute: typeof AiRoute
  ComparerRoute: typeof ComparerRoute
  DebouchesRoute: typeof DebouchesRoute
  ResultatsRoute: typeof ResultatsRoute
  SpecialtiesRoute: typeof SpecialtiesRoute
  SpecialiteIdRoute: typeof SpecialiteIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/specialties': {
      id: '/specialties'
      path: '/specialties'
      fullPath: '/specialties'
      preLoaderRoute: typeof SpecialtiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resultats': {
      id: '/resultats'
      path: '/resultats'
      fullPath: '/resultats'
      preLoaderRoute: typeof ResultatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debouches': {
      id: '/debouches'
      path: '/debouches'
      fullPath: '/debouches'
      preLoaderRoute: typeof DebouchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparer': {
      id: '/comparer'
      path: '/comparer'
      fullPath: '/comparer'
      preLoaderRoute: typeof ComparerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specialite/$id': {
      id: '/specialite/$id'
      path: '/specialite/$id'
      fullPath: '/specialite/$id'
      preLoaderRoute: typeof SpecialiteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  AiRoute: AiRoute,
  ComparerRoute: ComparerRoute,
  DebouchesRoute: DebouchesRoute,
  ResultatsRoute: ResultatsRoute,
  SpecialtiesRoute: SpecialtiesRoute,
  SpecialiteIdRoute: SpecialiteIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
